---
- name: Install gnupg
  become: yes
  ansible.builtin.apt:
    name: gnupg
    state: present

- name: Add Docker repository key
  become: yes
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker GPG key to APT keyring
  become: yes
  ansible.builtin.shell: gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg /etc/apt/trusted.gpg.d/docker.gpg

- name: Add Docker repository
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: 'deb [signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bookworm stable'
    create: yes

- name: Update APT cache
  become: yes
  ansible.builtin.apt:
    update_cache: yes

- name: Install Docker
  become: yes
  ansible.builtin.apt:
    name: docker-ce,docker-ce-cli,containerd.io
    state: present
