---
# tasks file for Linux-first-config
  - name: Install the latest version of Apache
    ansible.builtin.dnf:
     name: '*'
     state: latest
     update_cache: true
     update_only: true
    register: dnfupdate_status

  - name: Remove packages not needed anymore
    ansible.builtin.dnf:
     autoremove: true  
